apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    version: 2
    jsonData:
      version: 'Flux'
      organization: myorg
      defaultBucket: monitoring
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
